StockfolioOfficial/front-landing-career

package-lock.json, package.json, src/components/UI/molecules/default.tsx, src/components/UI/organisms/default.tsx, src/components/pages/default.tsx, src/components/templates/default.tsx
git clone 성공
필수 리뷰어:
---
- 내용
---
- 내용
---
- 내용
---
---
- 내용
=> git clone 성공

src/App.tsx, src/components/templates/Nav.tsx, src/styles/Inner.ts, src/styles/mixin.ts, src/utils/handleThemeKey.ts
필수 리뷰어: @lunathebright 
---
- 내용
nav바 생성 완료
- nav바 화면 구현 완료
- menu tap 이동 기능은 아직 구현 X
- 내용
---
---
- 내용
=> ADD: navbar 생성

src/components/UI/atoms/buttons/ArrowBtn.tsx, src/components/UI/molecules/HistoryListItem.tsx, src/components/UI/molecules/IntroduceListItem.tsx, src/components/UI/organisms/IntroduceList.tsx, src/components/UI/organisms/MacbookSlide.tsx, src/models/landingInterfaces.ts, src/stores/RootStore.ts, src/stores/SlideStore.ts
필수 리뷰어:
@euiyeonlee 
---
- 랜딩페이지 내 슬라이드 기능 구현
---
- 기능 구현 완료
---
- 내용
---
---
- 내용
=> feat(Slide): 맥북 슬라이드 기능 구현 - landing

src/App.tsx, src/components/UI/atoms/Labels/Label.tsx, src/models/commonInterfaces.ts
필수 리뷰어:
---
- 종류에 따른 레이아웃 구분 완료
---
- 신입/경력 label 완료
---
- 내용
---
---
- 내용
=> feat(Label): 종류에 따른 레이아웃 구분 완료

src/components/UI/organisms/RecruitMenuBar.tsx, src/components/templates/Nav.tsx, src/styles/Inner.ts
필수 리뷰어:
---
- 내용
---
- 내용
---
- 내용
---
---
- 내용
=> feat: nav바 수정

src/App.tsx, src/components/UI/organisms/RecruitMenuBar.tsx
필수 리뷰어: @lunathebright 
---
- 상단 menu바 center 정렬
- margin-left >> margin 양 옆으로 간격 수정
- 내용
---
---
- 내용
=> menu 간격 조정(center)

package-lock.json, package.json
필수 리뷰어:
---
- 내용
---
- 내용
---
- 내용
---
---
- 내용
=> install router type

src/assets/data/applicationForm.ts, src/components/UI/organisms/ApplicationEducation.tsx, src/components/UI/organisms/ApplicationIntroduction.tsx, src/components/UI/organisms/ApplicationPortfolio.tsx, src/components/pages/Application.tsx
필수 리뷰어:
---
- #66
- #67
- #51
- 변경 완료했습니다.
- 특이사항 없습니다.
- 적용확인하였습니다.
---
- 내용
=> [STORY] 지원서 페이지 QA  TASK #51,#66,#67 작업 완료

src/components/UI/organisms/ApplyNavBar.tsx, src/components/templates/ApplyForm.tsx, src/components/templates/ApplyList.tsx, src/stores/ApplyMenuStore.ts
---
- [TASK] #65 
---
- 전체 지원 탭 추가 (commit : fbf52f7)
---
- 전체 탭의 갯수를 표시하는 라벨을 찾아 해당 리스트의 갯수를 표시하게 해주는 부분에서 조금 시간이 걸렸습니다.
---
- 로컬에서 확인했습니다.
---
- 없습니다.
=> [TASK] #65 전체 지원 공고 탭 추가

src/App.tsx, src/assets/data/adminAccountForm.ts, src/assets/data/adminNotificationData.ts, src/components/UI/atoms/buttons/AdminBtn.tsx, src/components/UI/atoms/inputs/AdminInput.tsx, src/components/UI/atoms/texts/Heading4.tsx, src/components/templates/AdminAccount.tsx, src/components/templates/AdminNotiUpload.tsx, src/components/templates/AdminNotification.tsx, src/models/AdminAccountInterface.ts
---
- 내가 올린 공고 페이지 레이아웃 (commit : 601d9a2)
- 새로운 공고 올리기 페이지 레이아웃 (commit : 0e879e4)
---
- 공고 관리 페이지 레이아웃 작업을 진행했습니다.
---
- 웹 에디터를 아직 고르지 못해서 이 부분은 기능 구현 부분에서 다시 적용하도록 하겠습니다.
---
- 로컬에서 확인
---
- 새로운 공고 올리기 페이지에서 드롭다운 기능은 다음주에 적용해보도록 하겠습니다.
- 내가 올린 공고 페이지의 지원자 리스트 역시 차후에 변경하겠습니다.
- commit 메세지에서 실수로 같은 TASK를 닫는 명령어를 적었습니다. 이 부분 혹시 merge때 에러가 날까요?
=> [TASK] #82, #83 공고 관리 페이지 레이아웃

src/App.tsx, src/components/UI/organisms/AdminDescMain.tsx, src/components/pages/Admin.tsx, src/components/templates/AdminDesc.tsx
필수 리뷰어:
---
- 지원 공고 상세페이지 레이아웃 입니다.
---
- 이전에 있던 레이아웃을 사용하였습니다.
---
-  특이사항 없습니다. 
---
- 
---
-
=> [TASK] #79 지원공고 상세페이지 

src/App.tsx, src/components/pages/AdminLogin.tsx
필수 리뷰어:
---
- 어드민페이지레이아웃 완성
- 로그인 오류메세지 출력
- 레이아웃만 완성하였습니다. 
- 로그인 오류메세지 출력기능 추가하였습니다. 
- 특이사항없습니다.
-  백엔드와 연결하여 로그인 오류메세지 확인 완료
---
- recruit_id 가 필수로 설정되있어서 이후 백엔드 에서 수정후 삭제예정입니다.
=> [TASK] 로그인 레이아웃 및 로그인 오류메세지 출력 기능 추가(코멘트 반영) 

src/App.tsx, src/components/pages/AdminLogin.tsx, src/components/pages/AdminNav.tsx
필수 리뷰어:
---
- AdminNav 바 레이아웃 및 라우터 수정
---
- Admin NAV 바 완성후 라우터에 어드민 페이지에만 Adminnav바가 나오도록 수정하였습니다.  
- 
---
- 
---
-
=> AdminNav바 레이아웃, 라우터 수정

.eslintrc, src/App.tsx, src/components/UI/organisms/AdminMenuApplicant.tsx, src/components/UI/organisms/AdminNotice.tsx, src/components/pages/AdminApplicant.tsx, src/components/pages/AdminApplyNotice.tsx, src/components/pages/AdminCurrent.tsx
필수 리뷰어:
---
- 어드민 최근지원자 , 지원자리스트 공고리스트 레이아웃 완료 
- 레이아웃 완성했습니다. 
---
---
=> [TASK] 어드민 최근지원자 , 지원자리스트 공고리스트 레이아웃 완료 

package-lock.json, package.json, src/App.tsx, src/assets/data/adminAccountForm.ts, src/components/UI/atoms/buttons/AdminBtn.tsx, src/components/templates/AdminNotiUpload.tsx, src/models/AdminAccountInterface.ts, src/styles/globalStyle.ts, src/styles/typing.d.ts
---
- 웹 에디터 적용 (commit : ff760fc)
---
- 웹 에디터를 페이지에 적용 했습니다.
---
- 아직 백엔드와의 데이터 연동은 이뤄지지 않은 상황이라 해당 부분은 추후 적용하겠습니다.
---
- 로컬에서 작동 확인
---
- 없습니다.
=> [TASK] #98 웹 에디터 적용

src/App.tsx, src/assets/data/adminAccountForm.ts, src/components/UI/atoms/buttons/AdminBtn.tsx
---
- 공고 올리기 페이지 드롭다운 기능 구현 (commit : 5e7f466)
---
- 마감일 탭을 제외한 다른 드롭다운 버튼 기능 구현 완료
---
- mobx를 사용해야 한다는 생각에 갇혀서 시간소요가 많았습니다.
- 마감일 탭에는 캘린더 라이브러리를 적용해 보도록 하겠습니다.
---
- 로컬에서 작동 확인
---
- 공고 데이터를 관리하는 백엔드 개발자와 맞춰 보면 반드시 에러가 발생할 것 같은데
이 부분은 차후 수정하도록 하겠습니다.
=> [TASK] #98 드롭다운 기능 구현

src/App.tsx, src/assets/data/adminAccountForm.ts, src/components/UI/organisms/AdminAccountList.tsx, src/components/pages/AdminNav.tsx, src/components/templates/AdminAccount.tsx, src/models/AdminAccountInterface.ts
---
- 계정 관리 페이지에서 계정 수정 기능 구현 (commit : 6d9f017)
---
- 계정 관리 페이지에서 수정 버튼을 누른 뒤, 해당 계정 이름, 아이디, 비밀번호 변경 가능ㅈ
- 각 계정 별로 개별 적용 가능
---
- 계정마다 개별 적용을 해결하지 못했던 부분을, 컴포넌트 분리를 통해 해결했습니다.
---
- 로컬 실행 확인 (백엔드 데이터 통신은 아직 진행하지 못했습니다)
---
- 적용한 코드는 비슷한데, 컴포넌트를 분리하기 전에는 적용되지 않았던 기능이
컴포넌트 분리를 통해 개별 적용이 된 이유에 대해서 궁금합니다.
=> [TASK] #100 계정 수정 기능 구현

src/App.tsx, src/components/UI/organisms/AdminApplyNavbar.tsx, src/components/UI/organisms/AdminMenuApplicant.tsx, src/components/UI/organisms/AdminMenuBox.tsx, src/components/UI/organisms/AdminNotice.tsx, src/components/UI/organisms/ApplyDescMain.tsx, src/components/pages/Admin.tsx, src/components/pages/AdminApplicantList.tsx, src/components/pages/AdminApplyNotice.tsx, src/components/pages/AdminCurrent.tsx, src/components/pages/AdminLogin.tsx, src/components/pages/AdminMain.tsx, src/components/pages/AdminNav.tsx, src/components/templates/AdminDesc.tsx, src/components/templates/AdminNotiUpload.tsx, src/models/adminMainMenu.ts, src/models/applyInterfaces.ts, src/stores/AdminApplicantStore.ts, src/stores/AdminApplyMenuStore.ts, src/stores/AdminMenuboxStore.ts, src/stores/ApplyMenuStore.ts, src/stores/RootStore.ts, src/styles/globalStyle.ts
필수 리뷰어:
---
- 어드민 메인페이지 백엔드와 통신후 데이터 연결하기 
- 로그인시 유저이름 표시 
- 로그인시 유저이름표시 완료 
- 백엔드와 데이터 확인 완료 
- 어드민 메인페이지의 데이터 연결은 지원자리스트의 경력계산 부분만 제외 하면 완료되었습니다. 
- 아직 데이터 연결이 완전하지는 않아서 추후 수정이 필요할것 같습니다. 
- 데이터 통신간에 어려움이 많았습니다. 
---
- 이후 수정을 통해 문제없이 연결완료 하겠습니다.
=> [TASK] 어드민 메인페이지 연결

src/App.tsx, src/assets/data/adminAccountForm.ts, src/assets/data/adminApplicantData.ts, src/assets/data/adminCommentForm.ts, src/components/UI/atoms/TimeForm.tsx, src/components/UI/atoms/inputs/AdminInput.tsx, src/components/UI/atoms/texts/Desc.tsx, src/components/UI/molecules/EvaluationBox.tsx, src/components/UI/organisms/AdminAccountList.tsx, src/components/UI/organisms/ApplicantComment.tsx, src/components/UI/organisms/ApplicantCommentBox.tsx, src/components/UI/organisms/ApplicantCommentList.tsx, src/components/UI/organisms/ApplicantPortfolio.tsx, src/components/UI/organisms/ApplicantProject.tsx, src/components/UI/organisms/ApplicantTitle.tsx, src/components/pages/AdminNav.tsx, src/components/templates/AdminAccount.tsx, src/components/templates/AdminApplicant.tsx, src/components/templates/AdminNotiUpload.tsx, src/config.ts, src/models/AdminAccountInterface.ts, src/styles/globalStyle.ts, src/styles/styled.d.ts, src/styles/theme.ts, src/utils/getToken.ts
---
- 계정 관리 페이지에서 계정 추가, 삭제, 수정 기능 구현 (commit : 25ff1bb)
- 지원자 상세 페이지에서 comment 추가 기능 구현 (commit: ef09958)
- comment 수정 및 삭제 기능 구현 (commit: 7502103)
---
- 계정 추가, 수정, 삭제 기능 구현 확인
- comment 추가 기능 구현 확인
- comment 평가에 따른 배경 색 변경 확인
- comment 수정 및 삭제 기능 구현 확인
---
- 기존에 생성된 계정의 비밀번호가 암호화가 되어 "*"로 숨겨져 왔는데,
비밀번호를 건드리지 않고, 아이디와 이름만 수정해서 보낸 경우 백에서 비밀번호에 대한 에러가 발생해
수정 버튼을 누르면 비밀번호를 처음부터 다시 설정하도록 설정
- 계정 삭제 후 새로고침 이후 계정이 삭제 된 것을 확인할 수 있게 되는 오류 (추후 수정 예정)
---
- 로컬에서 구현 확인
---
- 백과 첫 통신을 하는 과정에서 에러도 많이 있고, 여전한 오류가 있기에
해당 부분은 차후 수정하며 진행하도록 하겠습니다.
=> [TASK] #99 #100 계정 추가, 수정, 삭제 기능 구현

src/components/UI/organisms/AdminDescMain.tsx, src/components/templates/AdminNotiUpload.tsx
---
- iframe 로 웹 에디터 내용 적용 (commit : 07e408c)
---
- 백엔드 데이터 받아와서 공고 창에 적용 확인
---
-
---
-  로컬에서 확인
---
- 없습니다
=> 웹 에디터 iframe 으로 활용
